- name: Task level variables
  hosts: local
  connection: local
  vars:
    COURSE: DevOps with AWS
    DURATION: 10HR
    TRAINER: John Doe
  tasks:
  - name: print course information
    vars:
      COURSE: Ansible
    ansible.builtin.debug:
      msg: "Hello {{ COURSE }}, Course Duration: {{ DURATION }}m Trainer {{ TRAINER }}"
  
  - name: print course information
    ansible.builtin.debug:
      msg: "Hello {{ COURSE }}, Course Duration: {{ DURATION }}m Trainer {{ TRAINER }}"
  