- name: variables from files
  hosts: local
  connection: local
  vars_files:
  - course.yaml
  tasks:
  - name: printing course information
    ansible.builtin.debug:
      msg: "Hello I'm learning Course: {{ COURSE }}, Duration: {{ DURATION }} with Trianer: {{ TRAINER }}"