- name: functions
  hosts: local
  connection: local
  vars:
    persons: "Ramesh,Suresh,Raheem,Joseph"
  tasks:
  - name: check undefined variable
    ansible.builtin.debug:
      msg: "Hello {{ person | default('John') }}"

  - name: print names
    ansible.builtin.debug:
      msg: "Hello {{ persons | split(',') }}"
  
  - name: convert map into list
    vars:
      course:
        name: ansible
        duration: 10HR
        trainer: Johndoe
    ansible.builtin.debug:
      msg: "Course Info {{ course | dict2items }}"

  - name: convert list into map
    vars:
      course:
        - { "key": "name", "value": "ansible"}
        - { "key": "duration", "value": "10HR"}
        - { "key": "trainer", "value": "Johndoe"}
    ansible.builtin.debug:
      msg: "Course Info {{ course | items2dict }}"
  
  - name: convert to uppercase
    vars:
      name: "John Doe"
    ansible.builtin.debug:
      msg: "{{ name | upper }}"

  - name: convert to lowercase
    vars:
      name: "John Doe"
    ansible.builtin.debug:
      msg: "{{ name | lower }}"

  - name: check IP address is valid or not
    vars:
      ip: "192.168.1.2"
    ansible.builtin.debug:
      msg: "{{ ip | ansible.utils.ipaddr }}"